apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-demo-pvc
  namespace: greendb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: shared
